### ISSUE TITLE
framework not found Pods_AppName

### ISSUE THREAD

**Issue by alexcroox** [microsoft/appcenter-sdk-cordova#100]
Trying to archive my app. Totally clean install of src-cordova to avoid any legacy issues.

```
ld: framework not found Pods_AppName
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### **Details**

My `PodFile`

```
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'AppName' do
	project 'AppName.xcodeproj'
	pod 'AppCenter', '~> 2.2.0'
	pod 'AppCenter/Analytics', '~> 2.2.0'
	pod 'AppCenter/Crashes', '~> 2.2.0'
end
```

1. Which SDK version are you using?
    - 0.3.6
2. Which OS version did you experience the issue on?
    - Xcode
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - "cordova-ios": "^5.0.1"
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - Xcode
5. What third party plugins are you using?
```
code-push 2.0.7 "CodePushAcquisition"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.6 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-code-push 1.11.20 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-purchase 8.1.1 "Purchase"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
```

It looks to me like the Pods_***.framework isn't installed:

![ss](https://cl.ly/12a06e2eed2f/Screenshot%202019-07-30%20at%2011.43.23.png)

**Comment by dtrabo** [comment]
Hi @alexcroox , thanks for reporting this. Are you sure the issue relates to App Center SDK?

**Comment by alexcroox** [comment]
I couldn't say if I'm honest. The fix if anyone else runs into this was to delete the .framework from the list in my screenshot above.

**Comment by alexcroox** [comment]
Looping back to this. This is definitely related to App Center SDK which has the following in `appcenter-shared` `plugin.xml`: `<pods use-frameworks="true">`.

This is apparently an old way of using cocopods and is causing a conflict with Firebase SDK which aparently will not work if the resulting `Podfile` includes `use_frameworks!`

**Comment by alexcroox** [comment]
Again to anyone else hitting a brick wall with this. If building your project in Xcode, you need to open YourProject.xcworkspace (NOT YourProject.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.

**Comment by helzgate** [comment]
For me I had to do a "cordova prepare" again to fix it.

**Comment by yuricamara** [comment]
> Again to anyone else hitting a brick wall with this. If building your project in Xcode, you need to open YourProject.xcworkspace (NOT YourProject.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.

I have the same problem with Ionic 4. But the build is by console. Please, what I am supposed to do?
