### ISSUE TITLE
ld: library not found for -lPods when running in XCode using Ionic

### ISSUE THREAD

**Issue by daviddickson** [microsoft/appcenter-sdk-cordova#103]
### **Description**

I installed the plugins per the installation instructions, did `ionic cordova prepare ios` and run in XCode I get a build error - `ld: library not found for -lPods`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create blank Ionic app.
2. Do `cordova platform add ios@5.0.0`
3. Follow steps at https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova

### **Details**

1. Which SDK version are you using?
    - Followed steps at https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova
2. Which OS version did you experience the issue on?
    - n/a
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova 8.1.2, Cocoapods 1.7.5, Ruby 2.3.7p45

**Comment by Jamminroot** [comment]
Hey, @daviddickson, thanks for getting in touch!
Can you tell me, which file are you opening in XCode? It looks like you are opening `xcodeproj` file, is that correct?

**Comment by daviddickson** [comment]
Correct.

**Comment by MatkovIvan** [comment]
@daviddickson CocoaPods generates `.xcworkspace`. It should be used instead of the `.xcodeproj` file.
