### ISSUE TITLE
Error with phonegap build while compiling for ios

### ISSUE THREAD

**Issue by Perh0rd** [microsoft/appcenter-sdk-cordova#113]
### **Description**

Hi, trying to compile on phone gap build after upgrading to CLI 9.0.0 and ios cordova 5.0.1, the compilation crash for ios. But works for Android.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Connect to phonegap build
2. Try to compile for ios

### **Details**

```
"plugman-151 install --platform ios --project /project --plugin cordova-plugin-appcenter-push --nohooks=.": Fetching plugin "cordova-plugin-appcenter-push" via npm
Installing "cordova-plugin-appcenter-push" at "0.4.0" for ios
Fetching plugin "cordova-plugin-appcenter-shared@0.4.0" via npm
Installing "cordova-plugin-appcenter-shared" at "0.4.0" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Failed to install 'cordova-plugin-appcenter-push': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
pod: Command failed with exit code 1
```

1. Which SDK version are you using?
    - 0.4.0 (shared)
2. Which OS version did you experience the issue on?
    -  iOS
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova 9.0.0 - cordova ios 5.0.1
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    -  Iphone 8
5. What third party plugins are you using?
```
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-background-geolocation 3.2.1 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-appcenter-analytics 0.4.0 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.4.0 "App Center Crashes for Cordova"
cordova-plugin-appcenter-push 0.4.0 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.4.0 "App Center shared code for Cordova"
cordova-plugin-background-fetch 5.6.0 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**Comment by annakocheshkova** [comment]
Hi there @Perh0rd ! As we already mentioned in the previous issue, this is not reproduced on our side. In order to tell you what happened, we need to see either the produced Podfile or the output from `pod install`, as this is clearly what failed the installation.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

**Comment by Perh0rd** [comment]
Hi, 

We cannot reproduce the pod install it's located on phonegap build into the cloud.

**Comment by annakocheshkova** [comment]
Hi @Perh0rd, we are not able to reproduce this locally so without any additional info I'm afraid we can't help much.

**Comment by Perh0rd** [comment]
Make an agreement with phone to make this work?

**Comment by annakocheshkova** [comment]
@Perh0rd What I mean is we need more logs than you are getting from phonegap. Is there a way to get more detailed logs related to iOS (Some setting in phonegap or so - I'm not quite familiar with this system), so that we could see what happens at `pod install` stage? 
I'm afraid a screen session won't help much in this case - we won't see anything new there.

**Comment by annakocheshkova** [comment]
I will also repeat here that's it's crucial that phonegap uses the lates cordova-ios (5 and higher) and cli (9 and higher). Otherwise it will fail with this message for sure.

**Comment by Perh0rd** [comment]
Hi, phonegap uses the last cli and ios version.

I will give you the detail of the log on next build I'm getting ready to put some code in production, I'm busy, But I'll come back here with more detail.

Thank you for your investigation.

**Comment by annakocheshkova** [comment]
No problem @Perh0rd, I will wait for your details, hope we will be able to get the issue resolved.

**Comment by vbraun** [comment]
I got the same error locally. Running `pod install` manually yields:
````
custoMac:cordova vbraun$ cd platforms/ios/
custoMac:ios vbraun$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AppCenter":
  In Podfile:
    AppCenter (~> 2.5.0)

None of your spec sources contain a spec satisfying the dependency: `AppCenter (~> 2.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
````
Manually running `pod repo update` slooooowly downloads 300MiB of cocoapods. After that the `cordova-plugin-appcenter-.*` install works.
