### ISSUE TITLE
Npm outdated

### ISSUE THREAD

**Issue by Towerism** [microsoft/appcenter-sdk-cordova#127]
Npm packages are outdated 0.5.0 when 0.5.1 is the latest on github. Our builds are failing and waiting on the bugfix in this new version

**Comment by GimpMaster** [comment]
+1 on this. Same issue. Please update NPM repo

**Comment by guperrot** [comment]
The 0.5.1 release process has been started yesterday and is still being tested.

It will happen soon but the latest github release is still 0.5.0, not 0.5.1: https://github.com/microsoft/appcenter-sdk-cordova/releases/tag/latest as of today is 0.5.0.

Thanks for your patience.

**Comment by Towerism** [comment]
@guperrot Thanks. I only saw the release commit for 0.5.1.

**Comment by annakocheshkova** [comment]
@Towerism now it is released, please check it out!
