### ISSUE TITLE
Cordova build failed - cordova-plugin-appcenter-push

### ISSUE THREAD

**Issue by PIXPOINT** [microsoft/appcenter-sdk-cordova#133]
### **Description**
BUILD FAILED
Cordova Build failed when installing "cordova-plugin-appcenter-push"

I created a new Cordova project and added the plugin "cordova-plugin-appcenter-push". After adding the plugin I can no longer run "cordova build".
The error message that appears:

`Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zul�ssig in Prolog.`

### **Repro Steps**

1. cordova create hello com.example.hello HelloWorld
2. cordova platform add android
3. cordova build (Success)
4. cordova plugin add cordova-plugin-appcenter-push
5. Edit config.xml (google-services.json)
6. cordova build --> BUILD FAILED

### **Details**

"cordova-android": "^8.1.0",
"cordova-plugin-appcenter-push": "^0.5.1",
"cordova-plugin-appcenter-shared": "^0.5.1"
Installed Android SDK: Android 9.0 / API Level 28

**Comment by russelarms** [comment]
Hi! Thank you for reaching out.
I'll look into it and get back to you soon.

**Comment by PIXPOINT** [comment]
I found out that it had to do with a faulty Android Studio installation after repeating everything in a virtual machine and there was no problem. After uninstalling Android Studio and manually deleting the folders:
C: \ Users \% Username% \ AppData \ Roaming
C: \ Users \% Username% \ AppData \ Local \ Android
C: \ Users \% Username% \. Android

Then cordova build works again
