### ISSUE TITLE
Framework tag with type=podspec is depreciated on iOS

### ISSUE THREAD

**Issue by T-Ev** [microsoft/appcenter-sdk-cordova#134]
### **Description**

I am using Phonegap Build CLI 9.0.0 to build a hybrid app for android and ios platforms. I am using both the analytics and crash plugins.

The problem I have is for ios only. In the plugin.xml files for these plugins the following line is no longer supported by the phonegap CLI:
`<framework src="AppCenter" type="podspec" spec="~> 2.5.0" />`

I understand this is kept for backward compatibility, but it still causes phonegap build to fail on the latest CLI. Is this tag still needed since the correct `<podspec>` tag is implemented right above it in all of the appcenter plugins?

**Error message From Build Log:**
Installing "cordova-plugin-appcenter-analytics" at "0.5.1" for ios
Fetching plugin "cordova-plugin-appcenter-shared@0.5.1" via npm
Installing "cordova-plugin-appcenter-shared" at "0.5.1" for ios
**"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.**
Running command: pod install --verbose
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:611:12)
pod: Command failed with exit code 1

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create account at build.phonegap.com
2. Upload any cordova project in .zip file. Make sure it is using the latest android and ios sdks and phonegap version: cli-9.0.0
3. Add the following to the config.xml file:
`<preference name="APPCENTER_ANALYTICS_ENABLE_IN_JS" value="false" />
    <plugin name="cordova-plugin-appcenter-analytics"  source="npm"/>    
    <plugin name="cordova-plugin-appcenter-crashes"  source="npm"/> `
4. add ios signing key to phonegap build and build the ios app.

### **Details**

1. Which SDK version are you using?
    - appcenter sdk 0.5.1 (latest)
2. Which OS version did you experience the issue on?
    - iOS - all of them
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova version 9.0.0
5. What third party plugins are you using?
https://github.com/Rohfosho/CordovaCallNumberPlugin.git   	git	*	9d1e5e4	android,ios,winphone
https://github.com/T-Ev/cordova-wheel-selector-plugin.git   	git	*	8b0ea3f	android,ios,winphone
cordova-plugin-appcenter-analytics   	npm	*	0.5.1	android,ios,winphone
cordova-plugin-appcenter-crashes   	npm	*	0.5.1	android,ios,winphone
cordova-plugin-audiotoggle   	npm	*	1.0.3	android,ios,winphone
cordova-plugin-background-mode   	npm	*	0.7.3	android,ios,winphone
cordova-plugin-battery-status   	npm	*	2.0.3	android,ios,winphone
cordova-plugin-console   	npm	*	1.1.0	android,ios,winphone
cordova-plugin-contacts   	npm	*	3.0.1	android,ios,winphone
cordova-plugin-contacts-phonenumbers   	npm	*	0.0.12	android,ios,winphone
cordova-plugin-customurlscheme   	npm	*	5.0.0	android,ios,winphone
cordova-plugin-device   	npm	*	2.0.3	android,ios,winphone
cordova-plugin-dialogs   	npm	*	2.0.2	android,ios,winphone
cordova-plugin-file   	npm	*	6.0.2	android,ios,winphone
cordova-plugin-flashlight   	npm	*	3.2.0	android,ios,winphone
cordova-plugin-geolocation   	npm	*	4.0.2	android,ios,winphone
cordova-plugin-globalization   	npm	*	1.11.0	android,ios,winphone
cordova-plugin-inappbrowser   	npm	*	3.2.0	android,ios,winphone
cordova-plugin-insomnia   	npm	*	4.3.0	android,ios,winphone
cordova-plugin-ios-contacts-permissions   	npm	*	n/a	ios
cordova-plugin-media   	npm	*	5.0.3	android,ios,winphone
cordova-plugin-network-information   	npm	*	2.0.2	android,ios,winphone
cordova-plugin-splashscreen   	npm	*	5.0.3	android,ios,winphone
cordova-plugin-statusbar   	npm	*	2.4.3	android,ios,winphone
cordova-plugin-vibration   	npm	*	3.1.1	android,ios,winphone
cordova-plugin-whitelist   	npm	*	1.3.4	android,ios,winphone
cordova-plugin-x-toast   	npm	*	2.7.2	android,ios,winphone
onesignal-cordova-plugin   	npm	2.4.5	2.4.5	android,ios,winphone
phonegap-plugin-local-notification   	npm	*	1.0.1	android,ios,winphone
skwas-cordova-plugin-datetimepicker   	npm	1.1.3	1.1.3	android,ios,winphone

**Comment by ilyashumihin** [comment]
Hi, @T-Ev!
Thanks for getting in touch.

I tested that on my mac, and couldn't reproduce the problem.
Could you send the cocoapods version, package.json and config.xml contents ?

**Comment by T-Ev** [comment]
I believe I resolved the issue. The error has to do with the cordova-ios version used by Phonegap build cli-9.0.0 (iOS 5.0.1). Apparently, some breaking changes have been made since then with regards to podbeans. I backdated this appcenter plugin to version 0.4.1 and it built fine.

Some change between version 0.4.1 and 0.5.0 causes this error. I believe it is the cordova-ios version.

**So for all those other folks that have this problem, simply load version 0.4.1 of this sdk.**

Sometime this year, the phonegap CLI will be updated to version 10, with the updated cordova-ios library, hopefully we can use the latest version of this appcenter sdk when that happens.

**Comment by T-Ev** [comment]
One more note. For others looking at this thread. Please use the latest version of this sdk for your android platform due to security fixes. Only load the older sdk version for your iOS platform.

**Comment by annakocheshkova** [comment]
Hi there. Indeed, this tag is deprecated but it's not what causes the build to fail. 
`pod install` fails at some stage and since you have phonegap, I understand that you can't explicitly run it and find out what. 
This could happen, for example, due to low cordova-ios version. In cordova-ios 5.0.0, they fixed a very important issue, that's why cordova-ios 5.0.0 is highly recommended (see [here](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#failed-to-install-plugin---pod-command-failed-with-exit-code-1)).
But as you say that it was already 5.0.0, it could be something else. 
Also, we haven't changed anything special between 0.4.1 and 0.5.0, at least cordova versions for sure.

Anyway, troubleshooting issues with phonegap could be tricky because we can't get the exact reason of the failure, so I'm glad the issue is resolved at least in this way. If you have any more info on it, feel free to reopen!
