### ISSUE TITLE
Issue installing app center plugins

### ISSUE THREAD

**Issue by bigor77** [microsoft/appcenter-sdk-cordova#137]
### **Description**

We have issues installing following plugins

```
cordova-plugin-appcenter-analytics
cordova-plugin-appcenter-crashes
```

### **Repro Steps**

1. cordova platforms remove ios
2. cordova platforms add ios

```
Using cordova-fetch for cordova-ios@^5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: #bundle id#
	Name: #app name#
iOS project created with cordova-ios@5.1.1
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.5.1" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose

[!] The `#app name# [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-#app name#/Pods-#app name#.debug.xcconfig'. This can lead to problems with the CocoaPods installation


[!] The `#app name# [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-#app name#/Pods-#app name#.release.xcconfig'. This can lead to problems with the CocoaPods installation

"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
cordova-plugin-appcenter-analytics depends on AppCenter@~> 2.5.0, which conflicts with another plugin. AppCenter@~> 1.13.1 is already installed and was not overwritten.
Running command: pod install --verbose
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/projects/#app name#/app/build/demo/engineerOnsite/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
pod: Command failed with exit code 31
```

We managed to fix it by setting correct version in plugin.xml (inside both plugins)

```
before
        <podspec>
            <config>
                <source url="https://github.com/CocoaPods/Specs.git"/>
            </config>
            <pods use-frameworks="true">
                <pod name="AppCenter/Crashes" spec="~> 2.5.0" />
            </pods>
        </podspec>

        <framework src="AppCenter" type="podspec" spec="~> 2.5.0" />

working one
        <podspec>
            <config>
                <source url="https://github.com/CocoaPods/Specs.git"/>
            </config>
            <pods use-frameworks="true">
                <pod name="AppCenter/Crashes" spec="~> 1.13.1" />
            </pods>
        </podspec>

        <framework src="AppCenter" type="podspec" spec="~> 1.13.1" />
```

After fixing it we managed to add ios platform, but then cordova build ios crashed with error

No known class method for selector 'hasReceivedMemoryWarningInLastSession'

https://github.com/microsoft/appcenter-sdk-cordova/blob/284f364fd140e5e92bfecf0d1e0210f0d3333222/cordova-plugin-appcenter-crashes/src/ios/AppCenterCrashesPlugin.m#L72

### **Details**

1. Which SDK version are you using?
    1.13.1
2. Which OS version did you experience the issue on?
    iOS: XCode Version 11.3.1 (11C504)
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    Cordova version 9.0.0
    Cocoapods Version 1.5.2
    ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    Xcode console
5. What third party plugins are you using?
cordova-plugin-appcenter-analytics 0.5.1 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.5.1 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.5.1 "App Center shared code for Cordova"
cordova-plugin-barcodescanner 0.7.4 "BarcodeScanner"
cordova-plugin-camera 4.0.4-dev "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-openfilenative 1.0.3 "Open File Native"

**Comment by russelarms** [comment]
@bigor77 appcenter plugins of version 0.5.1 depend on AppCenter pods 2.5.0, not on 1.3.1, so the fix is not correct regarding `cordova-plugin-appcenter-analytics 0.5.1` and others.
This line looks strange:
`AppCenter@~> 1.13.1 is already installed and was not overwritten.`
It seems that you still have appcenter 1.13.1 pods somewhere. Could you try it out on a fresh project? For me, it worked ok.
```
1. cordova create MyApp
2. cd ./MyApp && cordova platform add ios
3. cordova plugin add cordova-plugin-appcenter-analytics
4. cordova plugin add cordova-plugin-appcenter-crashes
5. cordova build ios
```

**Comment by bigor77** [comment]
@russelarms 
Thanks for your quick replay. I try with fresh project as you suggested and got error when trying to add first plugin

```
cordova plugin add cordova-plugin-appcenter-analytics
Installing "cordova-plugin-appcenter-analytics" for ios
Installing "cordova-plugin-appcenter-shared" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
Failed to install 'cordova-plugin-appcenter-shared': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/projects/MyApp/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Failed to install 'cordova-plugin-appcenter-analytics': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/projects/MyApp/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
pod: Command failed with exit code 31
```

**Comment by russelarms** [comment]
Have you tried `pod repo update`?

**Comment by bigor77** [comment]
Thanx Ruslan.

pod repo update helped.
