### ISSUE TITLE
Using App Center with Capacitor

### ISSUE THREAD

**Issue by cssolutionsllc** [microsoft/appcenter-sdk-cordova#138]
### **Description**

I followed the instructions from Ionic to install App Center
https://ionicframework.com/docs/native/app-center-analytics

When trying to enable app center in Main.ts
```

import { enableProdMode } from "@angular/core";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { AppCenterAnalytics } from "@ionic-native/app-center-analytics/ngx";
import { AppModule } from "./app/app.module";
import { environment } from "./environments/environment";

if (environment.production) {
  enableProdMode();
}

var analytics = new AppCenterAnalytics();
analytics
  .setEnabled(true)
  .then((result) => {
    console.log(result);
  })
  .catch((error) => {
    console.log(error);
  });

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.log(err));
```

Error is thrown:
`cordova_not_available`

Is this happening because I am running this as a responsive web page and not as an app? Can MS App Center be used with in a web page?

### **Details**

1. Which SDK version are you using?
    "@ionic-native/app-center-analytics": "^5.27.0"
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
   "cordova-plugin-appcenter-analytics": "^0.5.1"
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    Debugging web age
5. What third party plugins are you using?
   "cordova-plugin-appcenter-analytics": "^0.5.1"

**Comment by russelarms** [comment]
Hi, the SDK currently does not support use inside a web page.
