### ISSUE TITLE
Explanation on APP_SECRET

### ISSUE THREAD

**Issue by rahulchaube** [microsoft/appcenter-sdk-cordova#142]
Hello,
I am a little confused regarding what should be the APP_SECRET. Like i checked the apple developer account and google play console but didn't find any identifier with such name. Can  someone shed some more light on what is APP_SECRET referred to in android and apple world.

Regards,
Rahul

**Additional context**

**Comment by johnborges** [comment]
[App Secret Instructions](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova#2-getting-the-app-center-app-secret)

**Comment by Jamminroot** [comment]
Hey @rahulchaube, thanks for getting in touch. Long words short - APP_SECRET is the identifier used to identify applications generated on the App Center side, and should be treated as a password. 
For more details, kindly refer to the documentation.
