### ISSUE TITLE
Windows 7 install cordova-plugin-appcenter-analytics on a ionic 3 project

### ISSUE THREAD

**Issue by brianwang** [Microsoft/appcenter-sdk-cordova#22]
Failed to install 'cordova-plugin-appcenter-analytics': Error
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modu
les\cordova-lib\src\plugman\install.js:557:37
    at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordo
va\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Administrator\AppData\Roaming\npm\nod
e_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\n
pm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:749:13)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modu
les\cordova-lib\node_modules\q\q.js:509:49
    at flush (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Failed to restore plugin "cordova-plugin-appcenter-analytics" from config.xml. Y
ou might need to try adding it again. Error: Version of installed plugin: "cordo
va-plugin-appcenter-shared@0.1.2" does not satisfy dependency plugin requirement
 "cordova-plugin-appcenter-shared@^0.1.3". Try --force to use installed plugin a
s dependency.

I tried reinstall all plugins , still get this

I tried reinstall ionic@latest, still get this

I tried remove all node_modules , still get this.

**Comment by chazguerrero** [comment]
you will have to update your project.json to have the correct version of shared in it
        "cordova-plugin-appcenter-crashes": "^0.1.3",
        "cordova-plugin-appcenter-push": "^0.1.3",
        "cordova-plugin-appcenter-shared": "^0.1.3",

**Comment by sergey-akhalkov** [comment]
Hi @brianwang, @chazguerrero, sorry for the delayed response and thanks for reaching us.

>"cordova-plugin-appcenter-shared": "^0.1.3"

Just want to clarify - you should not add this module to your `config.xml` file due to it installs automatically while you are adding analytics/crash/push modules, please take a look at `config.xml` of `demoapp`:
https://github.com/Microsoft/appcenter-sdk-cordova/blob/d995bf4082f62959bdf83c8c3c97f17d35161baa/demoapp/config.xml#L35

Please let me know if you still see any issues or have any questions.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if you have any updates.
