### ISSUE TITLE
AppCenter is not defined in Ionic 3 (TypeScript) project

### ISSUE THREAD

**Issue by rroa** [Microsoft/appcenter-sdk-cordova#26]
I followed the discussion in #20 and even downloaded a sample project listed in the thread, but was not able to run this successfully.

This is the code I'm using to access the window object (borrowed from the mentioned closed issue) and the `AppCenter` object is still undefined.

```
export class HomePage {
  private webWiew: any = window;
  constructor(public navCtrl: NavController) {
    var success = function (result) {
      console.log("analytics " + (result) ? "enabled" : "disabled");
    }

    var error = function (error) {
      console.error(error);
    }

    this.webWiew.AppCenter.Analytics.isEnabled(success, error);
  }
}
```

**Comment by rroa** [comment]
[UPDATE] I was able to make this work from the devices. But the object is not available from the emulators nor the DOM.

**Comment by bmourat** [comment]
Hi @rroa 

Thanks for reporting this issue. There is indeed something going on, as I can't even make this work for real devices. We will investigate and keep you posted on this thread.

Best,
Murat

**Comment by jakevis** [comment]
Any word on this one by chance? I can get it to work on devices.. but the ionic serve system crashes out.

Following #20 - the details there work on devices well, but I get unable to get property 'analytics' of undefined or null when used in the ionic emulator.

![image](https://user-images.githubusercontent.com/10895705/38062485-fe9868cc-32a8-11e8-8b5d-1d25cce51050.png)

**Comment by max-mironov** [comment]
Hey guys, I've tried to start from scratch and looks like it is working for me (i'm on macOS/iOS).
I was able to run the project on emulator and tracked analytics.
Here is my repo with sample app I've tried (https://github.com/max-mironov/Ionic_Blank).

So could you please try it out and see if it works. If it doesn't work please share more info:
- output for `ionic info` 
- output for `cordova platform ls`
- output for `cordova plugin ls`
- are you able to run `ionic build` without any issues?
- what exact command you use to run the app?

Thanks!

**Comment by max-mironov** [comment]
Hi all, I'm closing the issue for now as of now response - but please feel free to reach us in case you still need any help with this.

**Comment by Huy-Vu** [comment]
Hi @max-mironov, I also have this issue, just like @jakevis , wondering what I have done wrong

<img width="383" alt="Screen Shot 2019-09-14 at 11 51 31 PM" src="https://user-images.githubusercontent.com/9127452/64916383-03560980-d74b-11e9-8b7f-a875bfc6fdaa.png">

Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/Users/a639791/.nvm/versions/node/v8.15.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 8 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 7.0.0
   NodeJS     : v8.15.0 (/Users/a639791/.nvm/versions/node/v8.15.0/bin/node)
   npm        : 6.4.1
   OS         : macOS Mojave
   Xcode      : Xcode 10.2.1 Build version 10E1001

**cordova platform ls**
Installed platforms:
  ios 5.0.0
Available platforms: 
  android ~7.1.1
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0

cordova plugin ls
cordova-plugin-appcenter-analytics 0.4.0 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.4.0 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.4.0 "App Center shared code for Cordova"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"

ionic build runs fine, only some warnings from ts.lint

**Comment by annakocheshkova** [comment]
Hi @Huy-Vu, could you share the output from after installation of the plugin? 
Does this happen on both platforms or just iOS?

**Comment by Huy-Vu** [comment]
@annakocheshkova 
So the plugin installation does not throw any error:
`cordova plugin add cordova-plugin-appcenter-analytics cordova-plugin-appcenter-crashes`
```
Adding cordova-plugin-appcenter-analytics to package.json
Saved plugin info for "cordova-plugin-appcenter-analytics" to config.xml
Adding cordova-plugin-appcenter-crashes to package.json
Saved plugin info for "cordova-plugin-appcenter-crashes" to config.xml
```
then I add ios platform
`cordova platform add ios@5.0.0`
```
Using cordova-fetch for cordova-ios@5.0.0
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: io.ionic.starter
        Name: MyApp
iOS project created with cordova-ios@5.0.0
Installing "cordova-plugin-appcenter-analytics" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.4.0" already fetched, using that version.
Installing "cordova-plugin-appcenter-shared" for ios
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Running command: pod install --verbose
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Installing "cordova-plugin-appcenter-crashes" for ios
Plugin dependency "cordova-plugin-appcenter-shared@0.4.0" already fetched, using that version.
Dependent plugin "cordova-plugin-appcenter-shared" already installed on ios.
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Dependent plugin "cordova-plugin-appcenter-shared" already installed on ios.
Installing "cordova-plugin-cocoapod-support" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-ionic-keyboard" for ios
Installing "cordova-plugin-ionic-webview" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
The preference "pods_ios_min_version" has been deprecated. Please use "deployment-target" instead.
Searching for new pods
Checking cordova-plugin-appcenter-analytics for pods.
cordova-plugin-appcenter-analytics requires pod: AppCenter
Checking cordova-plugin-appcenter-crashes for pods.
cordova-plugin-appcenter-crashes requires pod: AppCenter
Checking cordova-plugin-appcenter-shared for pods.
cordova-plugin-appcenter-shared requires pod: AppCenter
Checking cordova-plugin-device for pods.
Checking cordova-plugin-ionic-keyboard for pods.
Checking cordova-plugin-ionic-webview for pods.
Checking cordova-plugin-splashscreen for pods.
Checking cordova-plugin-statusbar for pods.
Checking cordova-plugin-whitelist for pods.
Checking config.xml for pods.
Installing pods
Sit back and relax this could take a while.
Analyzing dependencies

Downloading dependencies
Using AppCenter (2.3.0)
Generating Pods project
Integrating client project
Sending stats

Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.


[!] The `MyApp [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyApp/Pods-MyApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation


[!] The `MyApp [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyApp/Pods-MyApp.release.xcconfig'. This can lead to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

Updating ios build to use workspace.
Adding schemes
--save flag or autosave detected
Saving ios@~5.0.0 into config.xml file ...
```
There are warning about 'framework' tag and 'LD_RUNPATH_SEARCH_PATHS' but I think it should be fine since I got same for other project also. Building project from Xcode is fine, but the web page with AppCenter.Analytics.trackEvent() does not show up.

When I run ionic serve I got the Runtime Error cannot read property 'Analytics' 
`ionic serve`
```
> ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
[app-scripts] [23:49:15]  ionic-app-scripts 3.2.1 
[app-scripts] [23:49:15]  watch started ... 
[app-scripts] [23:49:15]  build dev started ... 
[app-scripts] [23:49:15]  clean started ... 
[app-scripts] [23:49:15]  clean finished in 4 ms 
[app-scripts] [23:49:15]  copy started ... 
[app-scripts] [23:49:16]  deeplinks started ... 
[app-scripts] [23:49:16]  deeplinks finished in 23 ms 
[app-scripts] [23:49:16]  transpile started ... 
[app-scripts] [23:49:19]  transpile finished in 3.18 s 
[app-scripts] [23:49:19]  preprocess started ... 
[app-scripts] [23:49:19]  preprocess finished in 1 ms 
[app-scripts] [23:49:19]  webpack started ... 
[app-scripts] [23:49:19]  copy finished in 3.40 s 
[app-scripts] [23:49:22]  webpack finished in 3.65 s 
[app-scripts] [23:49:22]  sass started ... 
[app-scripts] [23:49:23]  sass finished in 963 ms 
[app-scripts] [23:49:23]  postprocess started ... 
[app-scripts] [23:49:23]  postprocess finished in 6 ms 
[app-scripts] [23:49:23]  lint started ... 
[app-scripts] [23:49:23]  build dev finished in 7.97 s 
[app-scripts] [23:49:23]  watch ready in 8.06 s 

[INFO] Development server running!
       
       Local: http://localhost:8100
       External: http://10.0.0.162:8100, http://10.24.105.63:8100
       DevApp: BMICalculator@8100 on maclb105015
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[app-scripts] [23:49:26]  tslint: src/app/app.component.ts, line: 2 
[app-scripts]             'IonicPage' is declared but its value is never read. 
[app-scripts]        L1:  import { Component } from '@angular/core';
[app-scripts]        L2:  import { Platform, IonicPage } from 'ionic-angular';
[app-scripts]        L3:  import { StatusBar } from '@ionic-native/status-bar';
[app-scripts] [23:49:26]  tslint: src/pages/my-bmi/my-bmi.ts, line: 2 
[app-scripts]             'NavController' is declared but its value is never read. 
[app-scripts]        L1:  import { Component } from '@angular/core';
[app-scripts]        L2:  import { IonicPage, NavController, NavParams } from 'ionic-angular';
[app-scripts]        L3:  import { BmiProvider } from '../../providers/bmi/bmi';
[app-scripts] [23:49:26]  tslint: src/pages/my-bmi/my-bmi.ts, line: 2 
[app-scripts]             'NavParams' is declared but its value is never read. 
[app-scripts]        L1:  import { Component } from '@angular/core';
[app-scripts]        L2:  import { IonicPage, NavController, NavParams } from 'ionic-angular';
[app-scripts]        L3:  import { BmiProvider } from '../../providers/bmi/bmi';
[app-scripts]             All imports on this line are unused. 
[app-scripts] [23:49:26]  tslint: src/pages/my-bmi/my-bmi.ts, line: 4 
[app-scripts]        L3:  import { BmiProvider } from '../../providers/bmi/bmi';
[app-scripts]        L4:  import { NumberValueAccessor } from '@angular/forms/src/directives';
[app-scripts]        L5:  import { BMI } from '../../app/models/bmi.models';
[app-scripts] [23:49:26]  lint finished in 2.30 s 
```

I haven't tried adding platform android and running on Android Studio yet.

**Comment by annakocheshkova** [comment]
@Huy-Vu Could you check what's inside `platforms` > `ios` > `Pods` ?

**Comment by Huy-Vu** [comment]
@AnastasiaKubova , this is my Podfile in platform>ios>Podfiles
```
platform :ios, '10.0'
use_frameworks!
target 'MyApp' do
	pod 'AppCenter', '~> 2.3.0'
end
```
And inside Pods folder:
<img width="420" alt="Screen Shot 2019-09-16 at 11 10 43 AM" src="https://user-images.githubusercontent.com/9127452/64969859-b5d4bc00-d872-11e9-8543-80292aebb4f7.png">

**Comment by annakocheshkova** [comment]
Ok understood. Let me ask a couple of follow-up questions @Huy-Vu :
Do you have our plugin folders under **platfoms** > **ios**> **MyApp** > **Plugins** ?
Do you have plugins installed under **plugins** (from the root of the app)?
Does the app build fine from **XCode** (not command-line)?

**Comment by Huy-Vu** [comment]
Yes @annakocheshkova , I have all there plugin folder inside both root app plugins folder and ios>MyApp>Plugins.

<img width="527" alt="Screen Shot 2019-09-18 at 9 47 49 AM" src="https://user-images.githubusercontent.com/9127452/65154620-d67b4e00-d9f9-11e9-8241-62880e8d16a1.png">
<img width="461" alt="Screen Shot 2019-09-18 at 9 48 13 AM" src="https://user-images.githubusercontent.com/9127452/65154621-d67b4e00-d9f9-11e9-86ff-299243e3cf02.png">


Xcode build fine

**Comment by annakocheshkova** [comment]
What I mean is does the app have this errors if started from XCode? Also, are there any warnings during the build process itself?

**Comment by annakocheshkova** [comment]
Hey, we haven't heard from you in a while, do you have any updates? If so, please let us know and re-open the issue. Thanks!
