### ISSUE TITLE
AppCenter.Crashes not working on Android, property 'length' undefined

### ISSUE THREAD

**Issue by Perroquiet** [Microsoft/appcenter-sdk-cordova#27]
I have a property 'length' undefined error in my cordova when calling AppCenter.Crashes.(anymethod())

Cordova Android version: 5.2.2
Cordova version: 8.0.0
node version: 6.12.2
OS: Windows

<img src="https://image.ibb.co/nJhLYH/appcenter.png" alt="appcenter">

[https://image.ibb.co/nJhLYH/appcenter.png](https://image.ibb.co/nJhLYH/appcenter.png)

I tested this using USB Debugging on Chrome and it seems the error is in the cordova.js when calling the androidExec() function

<img src="https://preview.ibb.co/cigQ0x/androidexec.png" alt="androidexec" border="0" />

[https://preview.ibb.co/cigQ0x/androidexec.png](https://preview.ibb.co/cigQ0x/androidexec.png)

I also built a release version of the app but still no luck.

**Comment by max-mironov** [comment]
Closing this as we've publish 0.1.4 with fix. Please let us know if you see any issues.
