### ISSUE TITLE
Application crash on start with cordova-plugin-appcenter-push with ionic 3

### ISSUE THREAD

**Issue by janstrbik** [Microsoft/appcenter-sdk-cordova#29]
When I add plugin `cordova-plugin-appcenter-push` to my Ionic 3 application I am unable to run application, everytime on real device or emulator it crashes on the start with message "App {{appName}} has stopped. Restart the application". When I uninstall this `appcenter-push` plugin my Ionic app works perfect.

This is my 
`ionic info`
```
@ionic/cli-utils  : 1.19.1
ionic (Ionic CLI) : 3.19.1
cordova (Cordova CLI) : 8.0.0

@ionic/app-scripts : 3.1.2
Cordova Platforms  : android 6.3.0 browser 5.0.3
Ionic Framework    : ionic-angular 3.9.2

Node : v6.10.3
npm  : 3.10.10
OS   : Windows 10
```
and this is my plugin list
I tried to update other appcenter packages (`cordova-plugin-appcenter-shared`, `cordova-plugin-appcenter-analytics`), but without success. I use all three plugins (push, analytics and shared) on version `0.1.3`

**Comment by bmourat** [comment]
Hi @janstrbik 
You need to add FIREBASE_SENDER_ID preference to config.xml
```
<preference name="FIREBASE_SENDER_ID" value="'paste_firebase_sender_id_here'" />
```
Please note single quotes inside double quotes!
