### ISSUE TITLE
Error installing ...

### ISSUE THREAD

**Issue by levarberry** [Microsoft/appcenter-sdk-cordova#31]
Error message is:
Failed to install 'cordova-plugin-appcenter-push': undefined
Error: /bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by elamalani** [comment]
@levarberry Thanks for reporting, we will investigate this issue at our end.

**Comment by bmourat** [comment]
Hi @levarberry 

Does this happen only when installing push plugin or other plugins too? And one more question: What version of cordova, cocoapods, and ruby you are using?

Best,
Murat

**Comment by levarberry** [comment]
It happens with all of them.

Levar Berry
eDriven Solutions
www.edrivensolutions.com
(513)318-1360x101

On Fri, Mar 16, 2018 at 1:43 PM, Murat Baysangurov <notifications@github.com

**Comment by bmourat** [comment]
@levarberry 
What version of cordova, cocoapods, and ruby are you using?

**Comment by elamalani** [comment]
@levarberry We haven't heard from you. I'll close this issue for now but feel free to reach out to us in case of any questions.
