### ISSUE TITLE
Can't Find "getInstallId()" Method.

### ISSUE THREAD

**Issue by IamDLY** [Microsoft/appcenter-sdk-cordova#35]
I Need Get UUID.

**Comment by elamalani** [comment]
@IamDLY Thanks for using App Center. We will add this API in the SDK shortly, in a few weeks.

**Comment by annakocheshkova** [comment]
@IamDLY, thank you for your request. The feature is implemented now and is going to be released in short time. We will keep you updated on the progress.

**Comment by annakocheshkova** [comment]
@IamDLY, released with the [0.1.5](https://github.com/Microsoft/appcenter-sdk-cordova/releases/tag/0.1.5)!
