### ISSUE TITLE
AppCenterCrashes does not work

### ISSUE THREAD

**Issue by pcfjojo** [Microsoft/appcenter-sdk-cordova#37]
` this.AppCenterCrashes.setEnabled(true).then(() => {
          this.AppCenterCrashes.lastSessionCrashReport().then(report => {
              console.log('Crash report', report);
              this.AppCenterCrashes.generateTestCrash();
          });
       });`

AppCenterAnalytics works fine, but Crash report does not work.

Any idea?

**Comment by elamalani** [comment]
@pcfjojo Can you share more details :

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 8.1.0, iOS 11
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - e.g. Cordova version 8.0.0
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - e.g. Google Pixel 2 emulator, Samsung Galaxy S8 physical device
5. What third party plugins are you using?
    - e.g. run "cordova plugins list" command and share your output

**Comment by elamalani** [comment]
@pcfjojo We haven't heard back from you. Closing this issue but feel free to ping us if you have any questions.

**Comment by alelapeyre** [comment]
Hi, maybe same problem for me. With `generateTestCrash()` nothing appears on AppCenter but the lastSessionCrashReport() well returns the crash.

I'm using Ionic 3.

**Comment by alelapeyre** [comment]
Hi, maybe same problem for me. With `generateTestCrash()` nothing appears on AppCenter but the `lastSessionCrashReport()` well returns the crash.

### Versions
SDK version **0.1.5**
Tested OS : **Android 5.0.2** (Galaxy A3), and **Android 6.0** (emulator)
Cordova version **8.0.0**
Cordova platforms: **android 5.2.1**
Ionic **3.20.0**

### Plugins
cordova-plugin-appcenter-analytics 0.1.5 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.5 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by elamalani** [comment]
@alelapeyre Please look at these troubleshooting steps to make sure the SDK is set up correctly to send crash reports. You can enable verbose logging and share the console logs.
https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/android#crashes-dont-show-up-in-the-portal

**Comment by elamalani** [comment]
@alelapeyre Did you restart the application after the crash happened? You need to restart it for the crash log to be sent to App Center backend. From the logs you shared, it doesn't look like the crash log was sent to App Center by the SDK.

**Comment by bmourat** [comment]
Hey @alelapeyre 

Thanks for detailed and splitted logs :) The only reason for such behaviour i see in logs is this line:
```
06-28 11:09:30.794  6236  6236 D AppCenterCrashes: CrashesListener.shouldAwaitUserConfirmation returned true, wait
sending logs.
```

This means that in your config.xml `APPCENTER_CRASHES_ALWAYS_SEND ` parameter is set to `false`, you should change it to `true` and crash reporting should work.

**Comment by alelapeyre** [comment]
Hi @bmourat, thank you that's works ! 

But there is a small inconsistency between the doc and the code. In the doc (https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/cordova#analytics-preferences) the default value of `APPCENTER_CRASHES_ALWAYS_SEND` is `true` and in the code it's `false` (https://github.com/Microsoft/appcenter-sdk-cordova/blob/master/cordova-plugin-appcenter-crashes/src/android/AppCenterCrashesPlugin.java#L28).

**Comment by bmourat** [comment]
Thanks, @alelapeyre for pointing this out! I've sent PR for this #41.

**Comment by DennisSmolek** [comment]
I'm still having issues with this... 

I can't get the crashes to show on the portal. 

I can see a similar message with my test crash trigger, but when I restart the app I'm not seeing ANY AppCenter logs. 

My app IS getting analytics and codePush data so I l know it's connected...

I set my `ALWAYS_SEND` to `true` but not seeing any appcenter logs...
