### ISSUE TITLE
README.md is incorrect

### ISSUE THREAD

**Issue by tiptronic** [Microsoft/appcenter-sdk-cordova#39]
In the README.md of the sample app, it reads 

to run the app run script  'npm run ios' - but there is no such script

**Comment by bmourat** [comment]
Hey @tiptronic!

Thanks for pointing this out. This should be ```cordova run ios```

Best,
Murat

**Comment by elamalani** [comment]
@tiptronic We have updated the text in our sample app. Thanks for letting us know.
