### ISSUE TITLE
Error adding the plugin

### ISSUE THREAD

**Issue by bellalMohamed** [Microsoft/appcenter-sdk-cordova#48]
### **Description**

Can't add the plugin to my cordova project

###*ERROR MESSAGE*

Failed to install 'cordova-plugin-appcenter-shared': SyntaxError: Expected "/*", "//", or "{" but "u" found.
    at peg$buildStructuredError (/Users/zeal/Desktop/programming/workarea/zeal/zeal3/platforms/ios/cordova/node_modules/xcode/lib/parser/pbxproj.js:412:12)
    at Object.peg$parse [as parse] (/Users/zeal/Desktop/programming/workarea/zeal/zeal3/platforms/ios/cordova/node_modules/xcode/lib/parser/pbxproj.js:1886:11)
    at pbxProject.parseSync (/Users/zeal/Desktop/programming/workarea/zeal/zeal3/platforms/ios/cordova/node_modules/xcode/lib/pbxProject.js:46:24)
    at Object.parseProjectFile [as parse] (/Users/zeal/Desktop/programming/workarea/zeal/zeal3/platforms/ios/cordova/lib/projectFile.js:41:15)
    at Api.addPlugin (/Users/zeal/Desktop/programming/workarea/zeal/zeal3/platforms/ios/cordova/Api.js:223:33)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:749:13)

(node:3415) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Expected "/*", "//", or "{" but "u" found.
(node:3415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. cordova-plugin-appcenter-shared@0.1.6

### **Details**

1. Which SDK version are you using?
    - 1.6.0
2. Which OS version did you experience the issue on?
    - Installaion bug
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova version 8.0.0
5. What third party plugins are you using?
code-push 2.0.6 "CodePushAcquisition"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-push 0.1.7 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.1.6 "App Center shared code for Cordova"
cordova-plugin-apprate 1.3.0 "AppRate"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.12 "CodePush"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-fcm 2.1.2 "FCMPlugin"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-sms 1.0.5 "SMS"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
sentry-cordova 0.11.0 "Sentry"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.0 "Launch Navigator"

**Comment by jwallra** [comment]
I would recommend first updating to the latest cordova SDK (0.1.7).  Can you reproduce the issue if you pull the cordova repo and run the `cordova plugin add cordova-plugin-appcenter-shared` command in the demoapp folder, to see if it reproduces the issue?

**Comment by bellalMohamed** [comment]
I pulled the repo and successfully installed the plugin.

**Comment by jwallra** [comment]
Ok, I'm curious if it's one of the other plugins you have installed... Could you uninstall all AppCenter plugins, reinstall them, and make sure you're on the most recent version?  It doesn't seem like it based on the error, but it could be that your other plugins are interfering.  

Have you successfully added the App Center shared library before?  Have you added any other plugins recently, or have any insights into which ones might be causing a conflict?  Any other info you can provide would be helpful to narrow down the problem.

**Comment by bmourat** [comment]
@bellalMohamed 
What version of android platform are you using? Cause I've tried to install all those plugins in the list and there are some conflicts in versions. For example  plugin`cordova-plugin-compat` requires android platform version to be `<6.3.0` and some others require it to be `>=6.3.0`. Otherwize i don't see any other issues cause after installing all plugins which could be installed, i successfully installed appcenter-shared plugin

**Comment by bellalMohamed** [comment]
I removed all the plugins and tried to install the plugin but I got the same error, any ideas?

**Comment by bellalMohamed** [comment]
After this problem happened I can't open the project in xcode.

**Comment by bmourat** [comment]
You mean you tried to install the plugin on an empty project, without any plugins and got the same error? And what does Xcode say in this error? Are you able to run ios app from command line with `cordova run ios` command? If not could you provide minimal project on which i can reproduce this?

**Comment by bmourat** [comment]
Hey @bellalMohamed 
We haven't heard from you in a while, did you try running app not from Xcode but from the command line?

**Comment by clpolet** [comment]
I'll close the thread for now @bellalMohamed feel free to comment in and we'll reopen.
