### ISSUE TITLE
NPM Install will fail due to missing dependency

### ISSUE THREAD

**Issue by ButchMonkey** [Microsoft/appcenter-sdk-cordova#5]
Due to cordova-plugin-appcenter-shared not being on npm the install steps in the readme will fail.
```
cordova plugin add cordova-plugin-appcenter-analytics
cordova plugin add cordova-plugin-appcenter-crashes
cordova plugin add cordova-plugin-appcenter-push
```
All require appcenter-shared so this will need to be installed manually before these steps can be completed

**Comment by sergey-akhalkov** [comment]
Hi @ButchMonkey, thanks for reaching us! We are going to release initial versions of these npm packages on this week, so the install steps from the readme will become valid, sorry for the inconvenience and let us know if you see any other issues or have any questions, thanks!

**Comment by ButchMonkey** [comment]
Thanks, and no worries - I see its a fairly new release

**Comment by jpike88** [comment]
Please let us know what it's ready on this thread

**Comment by sergey-akhalkov** [comment]
Hey @ButchMonkey, @jpike88, we are going to make NPM releases today, we'll let you know if any updates.

**Comment by sergey-akhalkov** [comment]
@ButchMonkey, @jpike88, good news - we've released initials version for all modules:
https://www.npmjs.com/package/cordova-plugin-appcenter-analytics
https://www.npmjs.com/package/cordova-plugin-appcenter-crashes
https://www.npmjs.com/package/cordova-plugin-appcenter-push

Please note, that the `appcenter-sdk-cordova` currently is in **preview** state, so if you see any issues or have any questions - please let us know.
