### ISSUE TITLE
Crashes: `attachments` undefined

### ISSUE THREAD

**Issue by DazChong** [Microsoft/appcenter-sdk-cordova#54]
### **Description**

- With `APPCENTER_CRASHES_ALWAYS_SEND` = `true`, crashes logs no issue.
- With `APPCENTER_CRASHES_ALWAYS_SEND` = `false` & using `attachments`, object is undefined hence `.addTextAttachment()` will always throw exception.
- Then I set back the `APPCENTER_CRASHES_ALWAYS_SEND` = `true`, somehow the `AppCenter.Crashes.process(processFunction, errorCallback)` method still being called.

### **Details**

1. Which SDK version are you using?
    "cordova-plugin-appcenter-analytics": "^0.1.8",
    "cordova-plugin-appcenter-crashes": "^0.1.8",
    "cordova-plugin-appcenter-shared": "^0.1.8",

2. Which OS version did you experience the issue on?
    - Android 7.0 (NRD90M)
    - not yet test on iOS

3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - Cordova version 8.0.0
    - cordova-ios@4.4.0
    - cordova-android@6.3.0
    - Cocoapods 1.5.3
    - ruby 2.3.7p456
    - gem 2.5.2.3

4. What device version did you see this error on?  Were you using a simulator or a physical device?
    - Samsung Galaxy S6 physical device

5. What third party plugins are you using?
    - com.plugins.shortcut 0.1.1 "Home Shortcuts"
    - com.adi.plugin.keychainutil 0.0.1 "KeyChain Cordova Plugin"
    - com.bez4pieci.cookies 0.0.1 "Cookies"
    - com.simpleProdInc.calabashiOS 1.0.2 "CalabashiOS"
    - com.wongatech.cordova-disable-nsurl-cache 0.0.1-dev "CordovaDisableNSURLCache"
    - cordova-custom-config 3.1.2 "cordova-custom-config"
    - cordova-plugin-android-fingerprint-auth 1.3.1 "FingerprintAuth"
    - cordova-plugin-appcenter-analytics 0.1.8 "App Center Analytics for Cordova"
    - cordova-plugin-appcenter-crashes 0.1.8 "App Center Crashes for Cordova"
    - cordova-plugin-appcenter-shared 0.1.8 "App Center shared code for Cordova"
    - cordova-plugin-device 1.1.3 "Device"
    - cordova-plugin-email-composer 0.8.3 "EmailComposer"
    - cordova-plugin-jailbreak-detection 0.1.0 "Jailbreak Detection"
    - cordova-plugin-network-information 2.0.1 "Network Information"
    - cordova-plugin-root-detection 0.1.1 "Root Detection"
    - cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
    - cordova-plugin-splashscreen 4.1.0 "Splashscreen"
    - cordova-plugin-sslcertificatechecker 5.0.0 "SSL Certificate Checker"
    - cordova-plugin-statusbar 2.4.2-dev "StatusBar"
    - cordova-plugin-touchid 0.4.0 "Touch ID"
    - cordova-plugin-whitelist 1.3.0 "Whitelist"
    - cordova-sqlcipher-adapter 0.1.9 "Cordova sqlcipher adapter"
    - ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by max-mironov** [comment]
Hello @DazChong, thanks for reporting. 
Just have tried to reproduce your issue on fresh Cordova App and was able to receive text attachment with  `APPCENTER_CRASHES_ALWAYS_SEND = false`.

I've proceed the function as follows:
```
        var processFunction = function (attachments, sendCallback) {
            var textAttachment = "Hello attachment";
            for (var i = 0; i < attachments.length; i++) {
                // This is how you can send a text value along with the crash.
                attachments[i].addTextAttachment(textAttachment, "hello.txt");
            }
            sendCallback(true);
        };

        AppCenter.Crashes.process(processFunction, errorCallback);
```

Could you please share your code how you handle this (if it differs from mine above)?
Also please note that currently we have a limitation on the attachment size. From AppCenter docs:
```
The size limit is currently 1.4 MB on Android and 7 MB on iOS. Attempting to send a larger attachment will trigger an error.
```
Please check out and let us know if you do not exceed the limitation.

As for your last question: yep, method should be called if it is defined, the difference lies in the native part of the plugin, so if it set to `false` then this crash will not be sent by this function.

Please let us know if it was helpful.

**Comment by max-mironov** [comment]
Hey @DazChong, please let us know if you have a chance to look at this.

**Comment by max-mironov** [comment]
Hey @DazChong , thanks for getting back, I'll close the issue for now as it seems working and we can reopen it again when you get a chance to verify it and if you see any issues going further.
