### ISSUE TITLE
Create declaration (d.ts) files

### ISSUE THREAD

**Issue by conniey** [Microsoft/appcenter-sdk-cordova#64]
### **Description**

It would be nice if this included *.d.ts files so that we could get intellisense in VS Code while developing with this SDK.

The react-native SDK already has a *.d.ts files that could be leveraged:
* Ex) https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter-analytics/Analytics.d.ts

**Comment by max-mironov** [comment]
Hey @conniey, we've added declarations (currently in master): https://github.com/Microsoft/appcenter-sdk-cordova/pull/67
New version of SDK including this changes will be released really soon.

**Comment by conniey** [comment]
@max-mironov Thanks! Is this a plugin that is supported by your team? Or is it some other developer that pulls in your repo? https://ionicframework.com/docs/native/app-center-analytics/

**Comment by max-mironov** [comment]
@conniey thanks, this plugin is not supported by our team and seems that it is maintained by community.

**Comment by max-mironov** [comment]
Closing this as https://github.com/Microsoft/appcenter-sdk-cordova/releases/tag/0.3.0 has been released!
As usual please let us know if any questions or concerns here.
