### ISSUE TITLE
AppCenter requires a higher minimum deployment target

### ISSUE THREAD

**Issue by tribalboy3000** [Microsoft/appcenter-sdk-cordova#76]
![screen shot 2019-01-31 at 3 46 24 am](https://user-images.githubusercontent.com/2553727/52054093-fc161e80-2520-11e9-8e85-f2d37b3dfb09.png)

![screen shot 2019-01-31 at 4 17 21 am](https://user-images.githubusercontent.com/2553727/52054107-06381d00-2521-11e9-912d-9f1c3f4b8eee.png)

my podfile:
![screen shot 2019-01-31 at 6 15 45 am](https://user-images.githubusercontent.com/2553727/52054122-118b4880-2521-11e9-8439-f3e7327ba599.png)

What is the minimum deployment target? This is the only plugin that I get these errors. When I check: cordova plugin list it is there. So I preceded to try to set some analytics:

    AppCenter.Analytics.trackEvent('Api request', { Url: url}, eventSuccess, eventError);

Then I get a javascript error that says AppCenter variable cannot be found. I am assuming this is due to minimum deployment target issue? Been working on this for a couple days and cannot get this resolved.

I also tried:
         <preference name="deployment-target" value="10.0"

in config.xml

**Comment by annakocheshkova** [comment]
Good. I'm closing the issue, feel free to re-open it if you need or ping me in Intercom.
