### ISSUE TITLE
Unable to install through PhoneGap/Cordova

### ISSUE THREAD

**Issue by CrankyRoemer** [Microsoft/AppCenter-SDK-Cordova#80]
### **Description**
I was trying to setup the App Center SDK to my app so I modified my _config.xml_ which the information provided by this repository and the webpage https://appcenter.ms and I get an error in the "Shared" dependency, we originally created our project in DevExtreme and had no issues building and adding packages, but I cand add this SDK, If I remove it everything is back to normal.

### **config.xml**
  ```
<all other basic config settings>
  <plugin name="cordova-plugin-camera" />
  <plugin name="cordova-plugin-device" />
  <plugin name="cordova-plugin-dialogs" />
  <plugin name="cordova-plugin-file" />
  <plugin name="cordova-plugin-geolocation" />
  <plugin name="cordova-plugin-inappbrowser" />
  <plugin name="cordova-plugin-media" />
  <plugin name="cordova-plugin-media-capture" />
  <plugin name="cordova-plugin-network-information" />
  <plugin name="cordova-plugin-splashscreen" onload="true" />
  <plugin name="cordova-plugin-whitelist" />
  <plugin name="cordova-plugin-ios-longpress-fix" />
  <plugin name="cordova-plugin-statusbar" onload="true" />
  <plugin name="cordova-plugin-email" />
  <plugin name="cordova-pdf-generator" />
  <plugin name="cordova-plugin-keychain-touch-id" />
  <plugin name="cordova-plugin-app-version" />
  <plugin name="cordova-plugin-cocoapod-support" />
  <plugin name="cordova-plugin-appcenter-analytics" />
  <plugin name="cordova-plugin-appcenter-crashes" />
  <plugin name="cordova-plugin-appcenter-push" />
  <access origin="*" />
  <access origin="http://tickets.appshb.com" />
```

### **Details**

1. Which SDK version are you using?
    - e.g. 0.3.3
2. Which OS version did you experience the issue on?
    - N/A
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    - [PhoneGap - cli-6.5.0](https://build.phonegap.com/current-support)
    - [cordova-plugin-cocoapod-support](https://www.npmjs.com/package/cordova-plugin-cocoapod-support)

4. What device version did you see this error on?  
    - N/A

### **Output when trying to build app**
[download.txt](https://github.com/Microsoft/AppCenter-SDK-Cordova/files/2979515/download.txt)

**Comment by annakocheshkova** [comment]
Hi @CrankyRoemer ! Have you tried following the instructions from [Troubleshooting page](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#failed-to-install-plugin---pod-command-failed-with-exit-code-1)?

**Comment by CrankyRoemer** [comment]
> Hi @CrankyRoemer ! Have you tried following the instructions from [Troubleshooting page](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/cordova#failed-to-install-plugin---pod-command-failed-with-exit-code-1)?

Yes, I've tried it, and modified the my config.xml to look similar to the Troubleshooting page and also some post I found around, this is my full config file I use for PhoneGap, I use the portal https://build.phonegap.com/ to build the app

`<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
  <name>ApplicationTemplate</name>
  <author email="fpm_app@appshb.com" href="appshb.com">FPM Apps</author>
  <description>Fire Prevention Management - PROD</description>
  <platform name="ios">
    <preference name="pods_ios_min_version" value="9.0" />
    <preference name="pods_use_frameworks" value="true" />
    <preference name="deployment-target" value="9.0" />
    <preference name="UseSwiftLanguageVersion" value="4" />
  </platform>
  <preference name="permissions" value="none" />
  <preference name="prerendered-icon" value="true" />
  <preference name="android-windowSoftInputMode" value="adjustResize" />
  <preference name="SplashScreen" value="splash" />
  <preference name="SplashScreenDelay" value="60000" />
  <preference name="AutoHideSplashScreen" value="false" />
  <preference name="SplashShowOnlyFirstTime" value="false" />
  <preference name="FadeSplashScreen" value="true" />
  <preference name="ShowSplashScreenSpinner" value="true" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="StatusBarOverlaysWebView" value="false" />
  <preference name="StatusBarBackgroundColor" value="#005979" />
  <preference name="android-minSdkVersion" value="14" />
  <preference name="android-targetSdkVersion" value="22" />
  <preference name="iosExtraFilesystems" value="library,library-nosync,documents,documents-nosync,cache,bundle,root" />
  <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
  <preference name="iosPersistentFileLocation" value="Library" />
  <preference name="iosPersistentFileLocation" value="Compatibility" />
  <preference name="AndroidPersistentFileLocation" value="Internal" />
  <preference name="AndroidPersistentFileLocation" value="Compatibility" />
  <config-file platform="ios" parent="NSCameraUsageDescription" target="*-Info.plist" overwrite="true">
    <string>"Se solicita el uso de la camara para las observaciones"</string>
  </config-file>
  <config-file platform="ios" parent="NSPhotoLibraryUsageDescription" target="*-Info.plist" overwrite="true">
    <string>"Se solicita el uso de la camara para las observaciones"</string>
  </config-file>
  <config-file platform="ios" parent="NSLocationWhenInUseUsageDescription" target="*-Info.plist" overwrite="true">
    <string>"Se solicita el uso de la camara para las observaciones"</string>
  </config-file>
  <config-file platform="ios" parent="NSPhotoLibraryAddUsageDescription" target="*-Info.plist" overwrite="true">
    <string>"Se solicita el uso de la camara para las observaciones"</string>
  </config-file>
  <allow-navigation href="*" />
  <allow-navigation href="http://tickets.appshb.com" />
  <plugin name="cordova-plugin-cocoapod-support" />
  <plugin name="cordova-plugin-add-swift-support" />
  <plugin name="cordova-plugin-camera" />
  <plugin name="cordova-plugin-device" />
  <plugin name="cordova-plugin-dialogs" />
  <plugin name="cordova-plugin-file" />
  <plugin name="cordova-plugin-geolocation" />
  <plugin name="cordova-plugin-inappbrowser" />
  <plugin name="cordova-plugin-media" />
  <plugin name="cordova-plugin-media-capture" />
  <plugin name="cordova-plugin-network-information" />
  <plugin name="cordova-plugin-splashscreen" onload="true" />
  <plugin name="cordova-plugin-whitelist" />
  <plugin name="cordova-plugin-ios-longpress-fix" />
  <plugin name="cordova-plugin-statusbar" onload="true" />
  <plugin name="cordova-plugin-email" />
  <plugin name="cordova-pdf-generator" />
  <plugin name="cordova-plugin-keychain-touch-id" />
  <plugin name="cordova-plugin-app-version" />
  <plugin name="cordova-plugin-appcenter-analytics" />
  <plugin name="cordova-plugin-appcenter-crashes" />
  <plugin name="cordova-plugin-appcenter-push" />
  <access origin="*" />
  <access origin="http://tickets.appshb.com" />
</widget>`

**Comment by annakocheshkova** [comment]
@CrankyRoemer ok good. Yeah this is a tricky issue. There is by the way [one more solution to it](https://github.com/Microsoft/AppCenter-SDK-Cordova/issues/73#issuecomment-458986428). You can also read my messages in that thread to get a better understanding of why this is happening.

Anyway, what's inside your iOS folder? Are the any Pods? What's inside `podfile`? What happens if you run `pod install` from there (the error message I'm interested in).

Thank you!

**Comment by CrankyRoemer** [comment]
Hi @annakocheshkova , I'm not using Xcode for this but Visual Studio with the DevExtreme SDK on which it uses PhoneGap/Cordova for the structure with build in Widgets from the SDK, so when I export my project I get a zip folder so that I can build on https://build.phonegap.com, so there is no actual iOS folder for it in the project, please view the following screenshots.

I've used different cordova plugins before in other projects but I wanted to intergrate this one so that we can distribute the app insider our company with the AppCenter instead of the current method we are handling, I can still use it, but not being able to use the cordova features that they have is sad

![ViewOfVS](https://user-images.githubusercontent.com/24900896/54778389-72272f80-4c0c-11e9-86eb-9c8a33ccda64.PNG)

![ZipFolder](https://user-images.githubusercontent.com/24900896/54778396-76534d00-4c0c-11e9-869a-a92217a82520.PNG)

**Comment by annakocheshkova** [comment]
Ok I see, actually cordova-ios with the fix was released recently so you can try to use it:
`cordova platform add ios@5.0.0`

**Comment by CrankyRoemer** [comment]
I think its because PhoneGap does not support Cordova for iOS over 4.5.5 because I tried setting up the engine for iOS on 5.0.0, but until they release a new build with support for Cordova 5.0.0 I wont be able to install it, thanks for your time.

![ViewOfVS2](https://user-images.githubusercontent.com/24900896/54843055-68183600-4ccb-11e9-9288-b94aa22e3464.PNG)
![PhoneGap](https://user-images.githubusercontent.com/24900896/54843068-6c445380-4ccb-11e9-985c-702007515305.PNG)

**Comment by annakocheshkova** [comment]
@CrankyRoemer sorry to hear that! The release of cordova-ios 5 was made not long time ago, so I assume PhoneGap will support it in the nearest future. 
I'm closing this issue for now, feel free to re-open it when needed.
