### ISSUE TITLE
feat: Capacitor support

### ISSUE THREAD

**Issue by berhir** [microsoft/appcenter-sdk-cordova#89]
The ionic team is pushing everyone to use capacitor instead of cordova. Capacitor has support for cordova plugins and according to the documentation most of the cordova plugins should just work.

But I am struggling with the app center plugins in our project. They are working only partially. On android for example the java code of the plugins gets executed. But when I try to access them in the JavaScript code nothing happens and I see these warnings in the log:

```
W/Capacitor/Plugin/Console: Native: tried calling AppCenterAnalytics.trackEvent, but the AppCenterAnalytics plugin is not installed.
W/Capacitor/Plugin/Console: Install the AppCenterAnalytics plugin: 'ionic cordova plugin add cordova-plugin-appcenter-analytics'
W/Capacitor/Plugin/Console: Native: tried calling AppCenterPush.setEnabled, but the AppCenterPush plugin is not installed.
W/Capacitor/Plugin/Console: Install the AppCenterPush plugin: 'ionic cordova plugin add cordova-plugin-appcenter-push'
```

The global `AppCenter` object is there, but `AppCenter.Push` and `AppCenter.Analytics` are undefined.

I know this is only partially related to the cordova plugins, but maybe it's only a small thing that's preventing it to work with capacitor.
If someone with more experience in this topic can take a look and give a hint how to fix it would be awesome.

**Comment by annakocheshkova** [comment]
Hi @berhir! I have no experience in Capacitor, but I'll be glad to help you.

First of all, I want to determine your project structure - how did you create your project, Is it fresh **capacitor** project or **ionic** + **capacitor**? If it was ionic previously, did it work with our plugin?
You are saying that most of the cordova plugins should work, did you integrate any? If so, where do they store `.js` plugin files once the plugin is installed? The problem you are having is that apparently you don't have the plugin `.js` files, hence the error trying to call the App Center methods. I tried installing a random plugin in a capacitor project (`npm install cool-cordova-plugin`, according to the docs), but I see only `.java` files are imported but no `.js` files.
 
Could you please also check if there are files inside:
1. `plugins/` (if it exists, or some other folder similar to this in the root of the project)
2. `android/capacitor-cordova-android-plugins` (I'm pretty sure there are no App Center plugins here)
3. `android/platform_www/` or `platforms/android/platform_www/`
4. `android/app/src/main/java/com/microsoft`

I'll also ask if someone from my teammates has experience with capacitor, but I doubt anyone has.

**Comment by berhir** [comment]
Hi @annakocheshkova, thank you for your help!

We have started a new project with ionic + capacitor. So I don't know if it works without capacitor. But that's something I can try out in a demo project.

Yes, we are using other cordova plugins and they are working. For example this [sim plugin](https://ionicframework.com/docs/native/sim) and the [sqlite plugin](https://ionicframework.com/docs/native/sqlite).

The `.js` files of the plugins are stored in `android/app/src/main/assets/public/plugins`.

Your questions:

1. I don't see a `plugins/` folder or similar in the root of the android project
2. The `.java` files of the App Center plugins are in `android/capacitor-cordova-android-plugins/src/main/java/com/microsoft/azure/mobile/cordova`, though android studio shows it as `mobile/android/capacitor-cordova-android-plugins/src/main/java/com/Microsoft.azure.mobile.cordova`
3. I don't see a `www` folder. The `.js` files of my application are in `android/app/src/main/assets/public`
4. In `android/app/src/main/java` I see only the `MainActivity` of my application

Thanks again for your help and I hope we can find a solution.

**Comment by annakocheshkova** [comment]
Thanks @berhir I will take a look tomorrow again and see if we can make it work real fast. 
If it's just a matter of moving some folders around, or even downloading them and pasting in the right palce, I might be able help you. All in all, it's just a means to an end.
Otherwise, or probably anyway, it will be a feature request.

**Comment by annakocheshkova** [comment]
By the way @berhir can you point me to the part of documentation that you used to create a project, just so that I was sure I am doing the right thing.

**Comment by berhir** [comment]
Sure, I am following the instructions here: [Using Capacitor with Ionic](https://capacitor.ionicframework.com/docs/getting-started/with-ionic)

`ionic start myAppCenterApp tabs --capacitor`
`cd .\myAppCenterApp\`

Install the App Center Analytics plugin
`npm install cordova-plugin-appcenter-analytics`
`npm install @ionic-native/app-center-analytics`

Add the Analytics plugin to the code.
_app.module.ts_
```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { AppCenterAnalytics } from '@ionic-native/app-center-analytics/ngx';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [
    AppCenterAnalytics,
    StatusBar,
    SplashScreen,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

_app.component.ts_
```ts
import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

import { AppCenterAnalytics } from '@ionic-native/app-center-analytics/ngx';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
    private appCenterAnalytics: AppCenterAnalytics
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this.appCenterAnalytics.setEnabled(true).then(() => {
        this.appCenterAnalytics
          .trackEvent('My Event', { TEST: 'HELLO_WORLD' })
          .then(() => {
            console.log('Custom event tracked');
          });
      });
    });
  }
}
```
Then build the web app:
`ionic build`

Add the android project:
`npx cap add android`

Open the project in android studio:
`npx cap open android`

For now I am manually adding the APP_SECRET to the `android\app\src\main\res\xml\config.xml` file. I hope there is a better way but for now I can live with it.
```
  <preference name="APP_SECRET" value="_my_app_secret_" />
```

Then start the app and take a look at the log output.

**Comment by annakocheshkova** [comment]
@berhir vielen dank for such a detailed STR! 
So I've tried to fix it, but unsuccessfully for now. From our side, I will file a feature request to investigate on Capacitor support, but of course the estimate is not today or in a couple of days.
 
What I would suggest you to do right now is to open an issue in the [Capacitor repo](https://github.com/ionic-team/capacitor/issues/new), as this is what they are proposing as well: 
![image](https://user-images.githubusercontent.com/34677812/57924860-fa455080-78ae-11e9-906b-f310efb3dd8a.png). Feel free to get back to me in case of any additional info.

**Comment by berhir** [comment]
@annakocheshkova Thank you for your try! I followed your suggestion and opened an issue it the capacitor repo. Let's see if someone can give a hint why it's not working.

**Comment by jcesarmobile** [comment]
There are a few bugs (at least 2), but I think none is in this plugin.
One is `@ionic-native/app-center-analytics` is calling `AppCenterAnalytics.trackEvent` and not `AppCenter.Analytics.trackEvent`
The other was on Capacitor's `cordova_plugins.js` generation that was making the `AppCenter` clobber to overwrite the `AppCenter.Analytics` clobber, I've fixed that one already.

As this plugin already ship types I think you can use them instead of `@ionic-native/app-center-analytics` until that is fixed.

**Comment by annakocheshkova** [comment]
That was fast. Thanks @jcesarmobile! 
@berhir I will leave this issue open until your confirmation that it's working (well I hope it is now).

**Comment by berhir** [comment]
Hi @jcesarmobile, thank you for your help and the fix in Capacitor.
I have updated Capacitor and the Ionic Native App Center packages to the latest versions and now it works. Not sure if there was a problem in `@ionic-native/app-center-analytics` at all.

One thing I noticed is that the event listener added with `AppCenter.Push.addEventListener('notificationReceived', onNotificationReceived);` works only if the app is in foreground and not when I tap on a push notification.
I guess this is because Capacitor has it's own listener. Now I use the PushNotifications Plugin of Capacitor and everything works as expected.

Thanks again!

@annakocheshkova from my side this can be closed. Though it would still be nice to see native Capacitor support in the future :)

**Comment by annakocheshkova** [comment]
@berhir good to know. Yeah, the listener should fire in both states. Did you place it inside `onDeviceReady` method?

**Comment by berhir** [comment]
@annakocheshkova Yes, I placed it inside `onDeviceReady `. But it's working with the Capacitor Push plugin and I don't see a disadvantage in using it. So it's fine for me as it is. Thanks!

**Comment by parthnayak7448** [comment]
@berhir Can you tell me where you put app secret key for app centre in capacitor plugin?

**Comment by adibbz** [comment]
> @berhir Can you tell me where you put app secret key for app centre in capacitor plugin?

Did you ever figure this out? I don't see anything in the documentation.

**Comment by adibbz** [comment]
I finally got this working in iOS by adding the imports and start call ([https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#4-start-the-sdk](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/ios#4-start-the-sdk)) to `ios/App/App/AppDelegate.swift`

**Comment by cssolutionsllc** [comment]
Can you tell us where to put the app secret key? I manually added it to` android\app\src\main\res\xml\config.xml`, but the contents of the file are replaced when I run `ionic capacitor run android`

**Comment by johnborges** [comment]
Hi all. A [Capacitor community plugin](https://github.com/capacitor-community/appcenter-sdk-capacitor) is for App Center is in the works with dev builds being published.
