### ISSUE TITLE
The event is not triggered when you click on the notification in background mode.

### ISSUE THREAD

**Issue by maciejkoch** [microsoft/appcenter-sdk-cordova#90]
### **Description**

According to the: https://docs.microsoft.com/en-us/appcenter/sdk/push/cordova-android
If the push is received in background, the event is NOT triggered at receive time. The event is triggered when you click on the notification, but it isn't. It works when app is off or is in foreground mode. In background notification comes but after click the event is not triggered.

I use Ionic 4 with this plugin: https://ionicframework.com/docs/native/app-center-push

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add listener for "notificationReceived" event 
2. Go to background mode
3. Send notification
4. Click on notification
5. App is opened but event is not triggered

### **Details**

1. Which SDK version are you using?
    0.3.4
2. Which OS version did you experience the issue on?
    Android 8, Android 9
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
    Cordova version 8.0.0
4. What device version did you see this error on?  Were you using a simulator or a physical device?
   Nokia 7Plus, Huawei P10 Lite
5. What third party plugins are you using?
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-analytics 0.3.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-push 0.3.4 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.3.4 "App Center shared code for Cordova"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-ms-adal 0.10.1 "ADAL for Cordova"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlcipher-adapter 0.2.1 "Cordova sqlcipher adapter"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

**Comment by Jamminroot** [comment]
Hey, @maciejkoch, thanks for reporting this one; We've just checked out behaviour of the apps using sdk on cordova, and it seem to be an actual bug.
We will keep you updated in this thread.

**Comment by maciejkoch** [comment]
Hi,

I'm really happy that you took care of the issue :) When can we expect the release with this fix?

**Comment by annakocheshkova** [comment]
Hi @maciejkoch, this will be included in the June release.

**Comment by annakocheshkova** [comment]
@maciejkoch the bugfix is released now, could you please verify if all works. Thank you!

**Comment by maciejkoch** [comment]
It works perfect! Thank you.
