### ISSUE TITLE
Appcenter Android HttpException 503 | ReasonCode: TooManyMessagesInFlight

### ISSUE THREAD

**Issue by ivobrands** [microsoft/appcenter-sdk-cordova#99]
### **Description**
I tried to run AppCenter push notifications to my Android device. Something went wrong when started the app. 

`this.appCenterPush.setEnabled(true)` is runned succesfully. After runnen setEnabled the following error shows up:

`W/AppCenter: Try #1 failed and will be retried in 5705 ms
    com.microsoft.appcenter.http.HttpException: 503 - CorrelationId: d7df6123-4ce7-46f5-9385-c8a5153cd4e7  ReasonCode: TooManyMessagesInflight 
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:314)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:328)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:47)
        at android.os.AsyncTask$2.call(AsyncTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)`

### **Repro Steps**
Normal installation of cordova plugin + the installation of FCM. I can send notifications from Firebase to my device.

### **Details**

1. Which SDK version are you using?
    API 28
2. Which OS version did you experience the issue on?
    Android 9
3. What version of Cordova, Cordova platforms, Cocoapods, and Ruby are you using?
     8.1.2 (With Ionic)
4. What device version did you see this error on?  Were you using a simulator or a physical device?
    HUAWEI POT-LX1
5. What third party plugins are you using?

cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-advanced-http 2.0.9 "Advanced HTTP plugin"
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.3.6 "App Center Crashes for Cordova"
cordova-plugin-appcenter-push 0.3.6 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by guperrot** [comment]
Hi, sorry for the troubles, we had an incident on production between 7/22 3.20PM PST to 7/23 11.20AM PST that was causing 502 and 503 errors when sending logs from any SDK. It should be resolved by now. Can you test again? Sorry for the inconvenience.

**Comment by ivobrands** [comment]
Yes it is working now! thanks for your explain.
